import Head from 'next/head'
import styles from '../styles/Home.module.css'
import List from '../components/List'
import client from '../contentfulClient';

export async function getStaticProps(){

  const res = await client.getEntries({
    content_type: 'list'
  });


  return {
    props: {
      list: res.items,
    },
    revalidate: 100,
  }
}

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List list={list}/>
    </div>
  )
}
